# Implementation overview
# -----------------------
#
# The direct evaluator is based on the ellipsoidal truncation method of
# Deconinck, Heil, Bobenko, van Hoeij and Schmies, *Computing Riemann Theta
# Functions*, Mathematics of Computation 73 (2004), 1417-1442. A Cholesky
# factorization of Im(tau) is used to enumerate the required lattice points,
# with the truncation radius selected from an incomplete-gamma tail bound.
# Half-integer upper gamma factors use an elementary exponential upper bound
# followed by positive-term recurrence, avoiding repeated high-precision erfc
# evaluations while keeping the truncation estimate conservative.
#
# Within each row of the lattice enumeration, one exponential initializes the
# summand and adjacent terms are generated by multiplicative recurrence.
# Quantities depending only on the period matrix are cached with the working
# precision included in the cache identity. Derivative truncation radii use a
# small bounded cache with shift norms rounded upward, so a cached radius is
# conservative for every argument in its bucket.
#
# When a lattice-volume estimate predicts a worthwhile saving, a partial
# Siegel reduction is applied using integer translations, unimodular basis
# changes and one-coordinate symplectic inversions. The basis changes use the
# Lenstra-Lenstra-Lovasz (LLL) lattice basis reduction algorithm to obtain a
# shorter, less skewed basis and expose a short direction for inversion. These
# transformations are recorded so that arguments, characteristics, values and
# derivative jets can be mapped consistently between the original and reduced
# coordinates. The choice between direct and reduced evaluation is a
# performance heuristic, not part of the error criterion; both paths use the
# same truncation bound.

from .functions import ctx_lru_cache, defun

# Input validation and cached period data
# ---------------------------------------

def _matrix_tuple(A):
    """Return a matrix as an immutable tuple of row tuples."""
    return tuple(tuple(A[i, j] for j in range(A.cols))
                 for i in range(A.rows))


def _as_vector(ctx, value, name, length=None):
    """Convert a public vector argument to a tuple of scalars."""
    try:
        vector = ctx.matrix(value)
    except (TypeError, ValueError):
        raise ValueError(f"{name} must be a vector")
    if vector.cols != 1:
        raise ValueError(f"{name} must be a vector")
    if length is not None and vector.rows != length:
        raise ValueError(f"{name} must have length {length}")
    result = tuple(ctx.convert(vector[i]) for i in range(vector.rows))
    if not all(ctx.isfinite(x) for x in result):
        raise ValueError(f"{name} entries must be finite")
    return result


def _normalise_tau(ctx, tau):
    """Validate and symmetrise a Riemann matrix."""
    try:
        tau = ctx.matrix(tau)
    except (TypeError, ValueError):
        raise ValueError("tau must be a square matrix")
    if not tau.rows or tau.rows != tau.cols:
        raise ValueError("tau must be a nonempty square matrix")
    tau = tau.copy()
    for i in range(tau.rows):
        for j in range(tau.cols):
            tau[i, j] = ctx.convert(tau[i, j])
            if not ctx.isfinite(tau[i, j]):
                raise ValueError("tau entries must be finite")
    for i in range(tau.rows):
        for j in range(i):
            if not ctx.almosteq(tau[i, j], tau[j, i]):
                raise ValueError("tau must be symmetric")
            entry = (tau[i, j] + tau[j, i]) / 2
            tau[i, j] = tau[j, i] = entry
    return tau


def _normalise_characteristic(ctx, characteristic, genus):
    """Validate literal characteristic vectors."""
    if characteristic is None:
        zero = ctx.zero
        return (zero,) * genus, (zero,) * genus
    if not isinstance(characteristic, (list, tuple)) or len(characteristic) != 2:
        raise ValueError("characteristic must be a pair (a, b)")
    a = _as_vector(ctx, characteristic[0], "characteristic a", genus)
    b = _as_vector(ctx, characteristic[1], "characteristic b", genus)
    if any(ctx.im(x) for x in a + b):
        raise ValueError("characteristic entries must be real")
    return tuple(ctx.re(x) for x in a), tuple(ctx.re(x) for x in b)


def _normalise_derivative(derivative, genus):
    """Convert a derivative request to a multi-index."""
    if isinstance(derivative, int):
        if derivative < 0 or genus != 1 and derivative != 0:
            raise ValueError("integer derivative orders require genus 1")
        return (derivative,) if genus == 1 else (0,) * genus
    try:
        derivative = tuple(derivative)
    except TypeError:
        raise ValueError("derivative must be a nonnegative multi-index")
    if len(derivative) != genus:
        raise ValueError(f"derivative must have length {genus}")
    if any(not isinstance(d, int) or d < 0 for d in derivative):
        raise ValueError("derivative entries must be nonnegative integers")
    return derivative


@defun
# Period entries retain matrix factorizations, so keep this cache modest.
@ctx_lru_cache(maxsize=16)
def _rtheta_tau_data(ctx, tau_key):
    """Cache immutable Cholesky data depending only on tau."""
    genus = len(tau_key)
    X = ctx.matrix(genus)
    Y = ctx.matrix(genus)
    for i in range(genus):
        for j in range(genus):
            X[i, j] = ctx.re(tau_key[i][j])
            Y[i, j] = ctx.im(tau_key[i][j])
    try:
        # mpmath returns Y = L L^T; the enumeration uses T = L^T.
        T = ctx.cholesky(Y).T
    except (ValueError, ZeroDivisionError):
        raise ValueError("imaginary part of tau must be positive definite")
    invT = ctx.inverse(T)
    invT_frob = ctx.sqrt(ctx.fsum(invT[i, j] ** 2
                                  for i in range(genus)
                                  for j in range(genus)))
    # ||sqrt(pi) T n|| >= sqrt(pi)/||T^-1||_F for nonzero integer n.
    rho = ctx.sqrt(ctx.pi) / invT_frob
    value_radius = _truncation_radius(
        ctx, genus, (0,), rho, invT_frob, ctx.zero)
    scaled_radius = value_radius / ctx.sqrt(ctx.pi)
    if genus & 1:
        ball_volume = 2 * ctx.fprod(
            2 * ctx.pi / (2 * k + 1)
            for k in range(1, (genus + 1) // 2))
    else:
        ball_volume = ctx.fprod(
            ctx.pi / k for k in range(1, genus // 2 + 1))
    point_estimate = (ball_volume * scaled_radius ** genus
                      / ctx.fprod(abs(T[i, i]) for i in range(genus)))
    return (_matrix_tuple(X), _matrix_tuple(Y), _matrix_tuple(T),
            invT_frob, rho, value_radius, point_estimate)


# Truncation bounds and lattice enumeration
# -----------------------------------------

def _upper_gamma_half_integer_bounds(ctx, first_twice_s, last_twice_s, x):
    """Bound a consecutive range of integer and half-integer upper gammas."""
    exponential = ctx.exp(-x)
    sqrt_x = ctx.sqrt(x)
    values = {}
    for twice_s, s, value, power in (
            (1, ctx.mpf('0.5'), exponential / sqrt_x, sqrt_x),
            (2, ctx.one, exponential, x)):
        # sqrt(pi)*erfc(sqrt(x)) <= exp(-x)/sqrt(x) for x > 0.
        # Starting the half-integer recurrence from this bound keeps every
        # subsequent value conservative.  The integer base is exact.
        while twice_s <= last_twice_s:
            if twice_s >= first_twice_s:
                values[twice_s] = value
            value = s * value + power * exponential
            power *= x
            s += 1
            twice_s += 2
    # Account for nearest-rounding error accumulated by the positive-term
    # recurrences.  This is negligible compared with the tail-bound margin.
    # Eight eps per recurrence level comfortably covers its positive
    # arithmetic operations. Increasing this factor is safer but makes the
    # bound only negligibly more conservative.
    rounding_factor = 8
    guard = 1 + rounding_factor * (last_twice_s + 1) * ctx.eps
    return tuple(guard * values[twice_s]
                 for twice_s in range(first_twice_s, last_twice_s + 1))


def _tail_bounds(ctx, genus, degrees, radius, rho, invT_frob, shift_norm):
    """Bound several omitted differentiated Gaussian lattice tails."""
    x = (radius - rho / 2) ** 2
    scale = genus * ctx.power(2 / rho, genus) / 2
    transform = invT_frob / ctx.sqrt(ctx.pi)
    gamma_values = _upper_gamma_half_integer_bounds(
        ctx, genus, genus + max(degrees), x)
    results = []
    for degree in degrees:
        tail = ctx.fsum(
            ctx.binomial(degree, k) * shift_norm ** (degree - k)
            * transform ** k * gamma_values[k]
            for k in range(degree + 1))
        results.append((2 * ctx.pi) ** degree * scale * tail)
    return tuple(results)


def _truncation_radius(ctx, genus, degrees, rho, invT_frob, shift_norm):
    """Choose a radius giving working-precision absolute tail error."""
    degrees = tuple(sorted(set(degrees)))
    degree = max(degrees)
    threshold = (ctx.sqrt(genus + 2 * degree
                          + ctx.sqrt(genus ** 2 + 8 * degree)) + rho) / 2
    # A larger safety factor reduces the tail target and may enlarge the
    # summation ellipsoid. Eight leaves three guard bits beyond ctx.eps.
    tail_safety_factor = 8
    target = ctx.eps / tail_safety_factor
    high = max(ctx.one, threshold)
    while max(_tail_bounds(ctx, genus, degrees, high, rho,
                           invT_frob, shift_norm)) > target:
        high = 1 + 5 * high / 4
    low = threshold
    # More bisections tighten the conservative radius at additional setup
    # cost. Twelve adequately resolves the discrete ellipsoid boundary.
    radius_bisections = 12
    for unused in range(radius_bisections):
        middle = (low + high) / 2
        error = max(_tail_bounds(ctx, genus, degrees, middle, rho,
                                 invT_frob, shift_norm))
        if error > target:
            low = middle
        else:
            high = middle
    return high


def _shift_norm_bucket(ctx, shift_norm):
    """Round a shift norm upward to a reusable conservative bucket."""
    if not shift_norm:
        return ctx.zero
    exponent = max(0, ctx.mag(shift_norm))
    # More bucket bits reduce radius inflation but create more cache entries
    # and fewer hits. Five gives roughly 32 buckets per binary scale.
    shift_bucket_bits = 5
    step = ctx.ldexp(ctx.one, exponent - shift_bucket_bits)
    bucket = step * ctx.ceil(shift_norm / step)
    if bucket < shift_norm:  # pragma: no cover
        bucket += step
    return bucket


# Only scalar radii are retained. A 32-entry cap can retain first- and
# second-degree radii across a varied path without unbounded growth.
@defun
@ctx_lru_cache(maxsize=32)
def _rtheta_derivative_radius(ctx, genus, degrees, rho, invT_frob,
                              shift_bound):
    """Cache a derivative radius for an upper bound on the shift norm."""
    return _truncation_radius(
        ctx, genus, degrees, rho, invT_frob, shift_bound)


def _ellipsoid_rows(ctx, T, center, radius):
    """Yield contiguous first-coordinate rows in an ellipsoid."""
    genus = len(center)
    point = [0] * genus
    displacement = [ctx.zero] * genus

    def enumerate_coordinate(j, remaining):
        offset = ctx.fsum(T[j][k] * displacement[k]
                          for k in range(j + 1, genus))
        reach = ctx.sqrt(max(ctx.zero, remaining)) / abs(T[j][j])
        midpoint = center[j] - offset / T[j][j]
        lower = int(ctx.ceil(midpoint - reach))
        upper = int(ctx.floor(midpoint + reach))
        if not j:
            yield tuple(point[1:]), lower, upper
            return
        for value in range(lower, upper + 1):
            point[j] = value
            displacement[j] = value - center[j]
            row = T[j][j] * displacement[j] + offset
            new_remaining = remaining - row ** 2
            if new_remaining < 0:  # pragma: no cover
                continue
            yield from enumerate_coordinate(j - 1, new_remaining)

    yield from enumerate_coordinate(genus - 1, radius ** 2)


# Partial Siegel reduction
# ------------------------

def _congruence(ctx, matrix, transform):
    """Return transform.T * matrix * transform without integer coercion."""
    genus = len(transform)
    result = ctx.matrix(genus)
    for i in range(genus):
        for j in range(genus):
            result[i, j] = ctx.fsum(
                transform[k][i] * matrix[k, l] * transform[l][j]
                for k in range(genus) for l in range(genus))
    return result


def _lll_transform(ctx, Y):
    """Return an LLL-reduced unimodular transform of the Gram matrix Y."""
    genus = Y.rows
    transform = [[int(i == j) for j in range(genus)]
                 for i in range(genus)]

    def gram_schmidt():
        gram = _congruence(ctx, Y, transform)
        mu = [[ctx.zero] * genus for unused in range(genus)]
        norms = [ctx.zero] * genus
        for i in range(genus):
            norms[i] = gram[i, i] - ctx.fsum(
                mu[i][j] ** 2 * norms[j] for j in range(i))
            if norms[i] <= 0:  # pragma: no cover
                raise ValueError("failed to reduce imaginary part of tau")
            for k in range(i + 1, genus):
                mu[k][i] = (gram[k, i] - ctx.fsum(
                    mu[k][j] * mu[i][j] * norms[j]
                    for j in range(i))) / norms[i]
        return mu, norms

    index = 1
    steps = 0
    # This is a failure guard, not a normal stopping criterion. Increasing it
    # only permits more work on a pathologically slow LLL reduction.
    max_steps = 1000 * genus ** 2
    # The conventional LLL choice 3/4 balances reduction strength and work.
    lovasz_delta = ctx.mpf('0.75')
    while index < genus:
        steps += 1
        if steps > max_steps:  # pragma: no cover
            raise ValueError("LLL reduction did not converge")
        mu, norms = gram_schmidt()
        for j in range(index - 1, -1, -1):
            quotient = int(ctx.nint(mu[index][j]))
            if quotient:
                for i in range(genus):
                    transform[i][index] -= quotient * transform[i][j]
                mu, norms = gram_schmidt()
        if norms[index] >= ((lovasz_delta - mu[index][index - 1] ** 2)
                            * norms[index - 1]):
            index += 1
        else:
            for i in range(genus):
                transform[i][index], transform[i][index - 1] = (
                    transform[i][index - 1], transform[i][index])
            index = max(1, index - 1)
    return tuple(tuple(row) for row in transform)


def _transform_vector(ctx, transform, vector):
    """Return transform.T * vector."""
    genus = len(vector)
    return tuple(ctx.fsum(transform[j][i] * vector[j]
                          for j in range(genus))
                 for i in range(genus))


def _partial_inversion(ctx, tau):
    """Apply the first-coordinate symplectic inversion to tau."""
    genus = tau.rows
    t = tau[0, 0]
    coupling = tuple(tau[0, j] for j in range(1, genus))
    result = ctx.matrix(genus)
    result[0, 0] = -1 / t
    for j in range(1, genus):
        result[0, j] = result[j, 0] = coupling[j - 1] / t
    for i in range(1, genus):
        for j in range(1, genus):
            result[i, j] = (tau[i, j]
                            - coupling[i - 1] * coupling[j - 1] / t)
    return result, (t, coupling)


def _point_estimate(ctx, tau_key):
    """Estimate the value ellipsoid's lattice-point count by its volume."""
    return ctx._rtheta_tau_data(tau_key)[6]


@defun
# Reduced-period entries also retain matrices and transformation metadata.
@ctx_lru_cache(maxsize=16)
def _rtheta_reduction_data(ctx, tau_key):
    """Cache a partially Siegel-reduced tau and its generator metadata."""
    tau = ctx.matrix(tau_key)
    genus = tau.rows
    operations = []
    identity = tuple(tuple(int(i == j) for j in range(genus))
                     for i in range(genus))
    # This is a convergence guard. Raising it does not affect normal paths.
    max_reduction_steps = 100
    for unused in range(max_reduction_steps):
        # Replace tau by tau-B. For integral symmetric B, only diag(B)
        # shifts the zero-characteristic argument (by diag(B)/2).
        diagonal = []
        for i in range(genus):
            diagonal.append(int(ctx.nint(ctx.re(tau[i, i]))))
            tau[i, i] -= diagonal[-1]
            for j in range(i):
                nearest = int(ctx.nint(ctx.re(tau[i, j])))
                tau[i, j] -= nearest
                tau[j, i] -= nearest
        if any(diagonal):
            operations.append(("translate", tuple(diagonal)))

        # LLL puts a short vector first; a short first vector is precisely
        # what the following one-coordinate inversion improves.
        Y = ctx.matrix(genus)
        for i in range(genus):
            for j in range(genus):
                Y[i, j] = ctx.im(tau[i, j])
        transform = _lll_transform(ctx, Y)
        if transform != identity:
            tau = _congruence(ctx, tau, transform)
            operations.append(("basis", transform))

        if abs(tau[0, 0]) >= 1:
            break
        # This generator is the higher-genus analogue of tau -> -1/tau,
        # applied only to the first coordinate.
        tau, inversion = _partial_inversion(ctx, tau)
        operations.append(("invert", inversion))
    else:  # pragma: no cover
        raise ValueError("partial Siegel reduction did not converge")
    reduced_key = _matrix_tuple(tau)
    return (reduced_key, tuple(operations),
            _point_estimate(ctx, reduced_key))


def _apply_reduction(ctx, z, operations):
    """Transform a zero-characteristic argument through Siegel generators."""
    z = tuple(z)
    factor = ctx.one
    for kind, data in operations:
        if kind == "translate":
            z = tuple(z[i] + ctx.mpf(data[i]) / 2
                      for i in range(len(z)))
        elif kind == "basis":
            z = _transform_vector(ctx, data, z)
        else:
            t, coupling = data
            first = z[0]
            factor *= (ctx.exp(-ctx.pi * ctx.j * first ** 2 / t)
                       / ctx.sqrt(-ctx.j * t))
            z = ((first / t,)
                 + tuple(z[i] - coupling[i - 1] * first / t
                         for i in range(1, len(z))))
    return z, factor


def _zero_characteristic_form(ctx, z, tau_key, a, b):
    """Express a theta value with characteristic using theta[0, 0]."""
    genus = len(z)
    shifted = tuple(
        z[i] + b[i] + ctx.fsum(tau_key[i][j] * a[j]
                                for j in range(genus))
        for i in range(genus))
    quadratic = ctx.fsum(a[i] * tau_key[i][j] * a[j]
                         for i in range(genus) for j in range(genus))
    linear = ctx.fsum(a[i] * (z[i] + b[i]) for i in range(genus))
    factor = ctx.exp(ctx.pi * ctx.j * quadratic
                     + 2 * ctx.pi * ctx.j * linear)
    return shifted, factor


def _reduce_zero_argument(ctx, z, tau_key):
    """Reduce a zero-characteristic value argument modulo its periods."""
    X_key, Y_key = ctx._rtheta_tau_data(tau_key)[:2]
    genus = len(z)
    coefficients = ctx.lu_solve(
        ctx.matrix(Y_key), ctx.matrix([ctx.im(value) for value in z]))
    n = tuple(int(ctx.nint(coefficients[i])) for i in range(genus))
    real_residual = tuple(
        ctx.re(z[i]) - ctx.fsum(X_key[i][j] * n[j]
                                for j in range(genus))
        for i in range(genus))
    m = tuple(int(ctx.nint(value)) for value in real_residual)
    reduced = tuple(ctx.mpc(
        real_residual[i] - m[i],
        ctx.im(z[i]) - ctx.fsum(Y_key[i][j] * n[j]
                                for j in range(genus)))
        for i in range(genus))
    quadratic = ctx.fsum(n[i] * tau_key[i][j] * n[j]
                         for i in range(genus) for j in range(genus))
    linear = ctx.fsum(n[i] * reduced[i] for i in range(genus))
    factor = ctx.exp(-ctx.pi * ctx.j * quadratic
                     - 2 * ctx.pi * ctx.j * linear)
    return reduced, factor, n


# Derivative transformation and jet composition
# ---------------------------------------------

def _add_polynomial_term(ctx, polynomial, index, value):
    """Add one coefficient to a sparse multivariate polynomial."""
    polynomial[index] = polynomial.get(index, ctx.zero) + value


def _multiply_polynomials(ctx, left, right, bounds):
    """Multiply sparse polynomials, truncating to componentwise bounds."""
    result = {}
    for left_index, left_value in left.items():
        for right_index, right_value in right.items():
            index = tuple(left_index[i] + right_index[i]
                          for i in range(len(bounds)))
            if all(index[i] <= bounds[i] for i in range(len(bounds))):
                _add_polynomial_term(
                    ctx, result, index, left_value * right_value)
    return result


def _multiindices(genus, degree):
    """Yield multi-indices through degree in graded reverse lexicographic order."""
    index = [0] * genus

    def generate(position, remaining):
        if position == genus - 1:
            index[position] = remaining
            yield tuple(index)
            return
        for value in range(remaining, -1, -1):
            index[position] = value
            yield from generate(position + 1, remaining - value)

    for total_degree in range(degree + 1):
        yield from generate(0, total_degree)


def _exp_polynomial(ctx, exponent, bounds):
    """Return the truncated power series of exp(exponent)."""
    zero = (0,) * len(bounds)
    result = {zero: ctx.one}
    term = {zero: ctx.one}
    for order in range(1, sum(bounds) + 1):
        term = _multiply_polynomials(ctx, term, exponent, bounds)
        for index, value in term.items():
            _add_polynomial_term(ctx, result, index,
                                 value / ctx.factorial(order))
    return result


def _linear_power(ctx, coefficients, order, bounds):
    """Expand a power of a linear form as a truncated polynomial."""
    zero = (0,) * len(bounds)
    result = {zero: ctx.one}
    linear = {}
    for i, value in enumerate(coefficients):
        if value:  # pragma: no branch
            index = tuple(int(i == j) for j in range(len(bounds)))
            linear[index] = value
    for unused in range(order):
        result = _multiply_polynomials(ctx, result, linear, bounds)
    return result


def _reduced_jet_data(ctx, z, tau_key, a, b, operations, reduced_key):
    """Transform an argument while retaining its local jet data."""
    genus = len(z)
    transformed, factor = _zero_characteristic_form(
        ctx, z, tau_key, a, b)
    jacobian = [[ctx.one if i == j else ctx.zero for j in range(genus)]
                for i in range(genus)]
    # For a local increment h, transformed(z+h) = transformed(z) + J*h.
    # ``exponent`` stores the nonconstant part of the logarithm of every
    # accumulated exponential prefactor as a sparse polynomial in h.
    exponent = {}
    for i, value in enumerate(a):
        index = tuple(int(i == j) for j in range(genus))
        _add_polynomial_term(
            ctx, exponent, index, 2 * ctx.pi * ctx.j * value)

    for kind, data in operations:
        if kind == "translate":
            transformed = tuple(
                transformed[i] + ctx.mpf(data[i]) / 2
                for i in range(genus))
        elif kind == "basis":
            transformed = _transform_vector(ctx, data, transformed)
            jacobian = [[ctx.fsum(data[k][i] * jacobian[k][j]
                                  for k in range(genus))
                         for j in range(genus)] for i in range(genus)]
        else:
            t, coupling = data
            first = transformed[0]
            first_row = tuple(jacobian[0])
            scale = -ctx.pi * ctx.j / t
            factor *= ctx.exp(scale * first ** 2) / ctx.sqrt(-ctx.j * t)
            for i in range(genus):
                linear_index = tuple(int(i == j) for j in range(genus))
                _add_polynomial_term(
                    ctx, exponent, linear_index,
                    2 * scale * first * first_row[i])
                for j in range(genus):
                    quadratic_index = tuple(
                        int(i == k) + int(j == k) for k in range(genus))
                    _add_polynomial_term(
                        ctx, exponent, quadratic_index,
                        scale * first_row[i] * first_row[j])
            transformed = ((first / t,)
                           + tuple(transformed[i]
                                   - coupling[i - 1] * first / t
                                   for i in range(1, genus)))
            jacobian = ([[value / t for value in first_row]]
                        + [[jacobian[i][j]
                            - coupling[i - 1] * first_row[j] / t
                            for j in range(genus)]
                           for i in range(1, genus)])

    transformed, argument_factor, period_shift = _reduce_zero_argument(
        ctx, transformed, reduced_key)
    factor *= argument_factor
    for j in range(genus):
        index = tuple(int(i == j) for i in range(genus))
        coefficient = -2 * ctx.pi * ctx.j * ctx.fsum(
            period_shift[i] * jacobian[i][j] for i in range(genus))
        _add_polynomial_term(ctx, exponent, index, coefficient)
    return transformed, factor, tuple(tuple(row) for row in jacobian), exponent


def _compose_reduced_derivative(ctx, derivatives, values, factor, jacobian,
                                exponent, derivative):
    """Apply the prefactor, chain and product rules to one derivative."""
    genus = len(derivative)
    theta_polynomial = {}
    zero_index = (0,) * genus
    for multiindex, value in zip(derivatives, values):
        polynomial = {zero_index: ctx.one}
        denominator = ctx.one
        for i, order in enumerate(multiindex):
            if order:
                polynomial = _multiply_polynomials(
                    ctx, polynomial,
                    _linear_power(ctx, jacobian[i], order, derivative),
                    derivative)
                denominator *= ctx.factorial(order)
        for index, coefficient in polynomial.items():
            _add_polynomial_term(
                ctx, theta_polynomial, index,
                value * coefficient / denominator)

    prefactor_polynomial = _exp_polynomial(ctx, exponent, derivative)
    result = _multiply_polynomials(
        ctx, prefactor_polynomial, theta_polynomial, derivative)
    derivative_factorial = ctx.fprod(
        ctx.factorial(order) for order in derivative)
    return factor * derivative_factorial * result.get(derivative, ctx.zero)


def _rtheta_reduced_derivatives(ctx, z, tau_key, a, b, requested,
                                operations, reduced_key):
    """Evaluate requested derivatives after one modular transformation."""
    genus = len(z)
    degree = max(sum(derivative) for derivative in requested)
    transformed, factor, jacobian, exponent = _reduced_jet_data(
        ctx, z, tau_key, a, b, operations, reduced_key)
    derivatives = tuple(_multiindices(genus, degree))
    zeros = (ctx.zero,) * genus
    values = _rtheta_sum(
        ctx, transformed, reduced_key, zeros, zeros, derivatives)
    return tuple(_compose_reduced_derivative(
        ctx, derivatives, values, factor, jacobian, exponent, derivative)
        for derivative in requested)


# Direct lattice summation
# ------------------------

def _rtheta_is_real_slice(ctx, X, shift, a):
    """Return whether lattice pairing makes every requested derivative real."""
    genus = len(a)
    return (all(ctx.isint(2 * value) for value in a) and not any(shift)
            and not any(X[i][j] for i in range(genus)
                        for j in range(genus)))


def _rtheta_value_sum(ctx, X, Y, T, center, radius, shift, a,
                      x_plus_b, growth):
    """Sum a theta value using a recurrence along each lattice row."""
    genus = len(center)
    pi = ctx.pi
    two_pi = 2 * pi
    pairs = [(i, j) for i in range(1, genus) for j in range(i)]
    real_diagonal = [-pi * Y[i][i] for i in range(genus)]
    real_off_diagonal = [-two_pi * Y[i][j] for i, j in pairs]
    imag_diagonal = [pi * X[i][i] for i in range(genus)]
    imag_off_diagonal = [two_pi * X[i][j] for i, j in pairs]
    imag_linear = [two_pi * x_plus_b[i] for i in range(genus)]
    # Advancing n[0] multiplies the adjacent-term ratio by exp(2*pi*j*tau00).
    ratio_step = ctx.exp(ctx.mpc(-two_pi * Y[0][0],
                                 two_pi * X[0][0]))

    form_length = genus + len(pairs)
    real_terms = [ctx.zero] * form_length
    imag_terms = [ctx.zero] * (form_length + genus)
    u = [ctx.zero] * genus
    shifted = [ctx.zero] * genus
    terms = []
    zero_characteristic = not any(a)
    scaled_radius = radius / ctx.sqrt(pi)
    for outer, lower, upper in _ellipsoid_rows(
            ctx, T, center, scaled_radius):
        n = (lower,) + outer
        for i in range(genus):
            u[i] = ctx.mpf(n[i]) if zero_characteristic else n[i] + a[i]
            shifted[i] = u[i] + shift[i]
            real_terms[i] = real_diagonal[i] * shifted[i] * shifted[i]
            imag_terms[i] = imag_diagonal[i] * u[i] * u[i]
            imag_terms[form_length + i] = imag_linear[i] * u[i]
        for k, (i, j) in enumerate(pairs, genus):
            real_terms[k] = (real_off_diagonal[k - genus]
                             * shifted[i] * shifted[j])
            imag_terms[k] = (imag_off_diagonal[k - genus]
                             * u[i] * u[j])
        exponent = ctx.mpc(ctx.fsum(real_terms), ctx.fsum(imag_terms))
        term = ctx.exp(exponent)
        terms.append(term)
        if lower == upper:
            continue
        # This is the exact ratio T(n + e0) / T(n) at the row's first point.
        ratio = ctx.exp(ctx.mpc(
            -two_pi * ctx.fsum(Y[0][i] * shifted[i]
                               for i in range(genus)) - pi * Y[0][0],
            two_pi * ctx.fsum(X[0][i] * u[i]
                              for i in range(genus))
            + pi * X[0][0] + imag_linear[0]))
        for unused in range(lower + 1, upper + 1):
            term *= ratio
            terms.append(term)
            ratio *= ratio_step
    result = growth * ctx.fsum(terms)
    if _rtheta_is_real_slice(ctx, X, shift, a):
        # Preserve the exact reality implied by pairing n with -n. Recurrence
        # rounding otherwise leaves a harmless tiny imaginary residue.
        result = ctx.mpc(ctx.re(result))
    return result


def _rtheta_derivative_sum(ctx, X, Y, T, center, radius, shift, a,
                           x_plus_b, growth, derivatives):
    """Sum derivatives using a recurrence along each lattice row."""
    genus = len(center)
    pi = ctx.pi
    two_pi = 2 * pi
    two_pi_j = two_pi * ctx.j
    pairs = [(i, j) for i in range(1, genus) for j in range(i)]
    real_diagonal = [-pi * Y[i][i] for i in range(genus)]
    real_off_diagonal = [-two_pi * Y[i][j] for i, j in pairs]
    imag_diagonal = [pi * X[i][i] for i in range(genus)]
    imag_off_diagonal = [two_pi * X[i][j] for i, j in pairs]
    imag_linear = [two_pi * x_plus_b[i] for i in range(genus)]
    # Advancing n[0] multiplies the adjacent-term ratio by exp(2*pi*j*tau00).
    ratio_step = ctx.exp(ctx.mpc(-two_pi * Y[0][0],
                                 two_pi * X[0][0]))

    form_length = genus + len(pairs)
    real_terms = [ctx.zero] * form_length
    imag_terms = [ctx.zero] * (form_length + genus)
    u = [ctx.zero] * genus
    shifted = [ctx.zero] * genus
    max_orders = [max(derivative[i] for derivative in derivatives)
                  for i in range(genus)]
    powers = [[ctx.one] * (order + 1) for order in max_orders]
    active_orders = [tuple((i, order) for i, order in enumerate(derivative)
                           if order) for derivative in derivatives]
    degrees = [sum(derivative) for derivative in derivatives]
    degree_factors = [ctx.one]
    for unused in range(max(degrees)):
        degree_factors.append(degree_factors[-1] * two_pi_j)
    sums = [[] for unused in derivatives]
    zero_characteristic = not any(a)
    scaled_radius = radius / ctx.sqrt(pi)
    for outer, lower, upper in _ellipsoid_rows(
            ctx, T, center, scaled_radius):
        n = (lower,) + outer
        for i in range(genus):
            u[i] = ctx.mpf(n[i]) if zero_characteristic else n[i] + a[i]
            shifted[i] = u[i] + shift[i]
            real_terms[i] = real_diagonal[i] * shifted[i] * shifted[i]
            imag_terms[i] = imag_diagonal[i] * u[i] * u[i]
            imag_terms[form_length + i] = imag_linear[i] * u[i]
            for order in range(1, max_orders[i] + 1):
                powers[i][order] = powers[i][order - 1] * u[i]
        for k, (i, j) in enumerate(pairs, genus):
            real_terms[k] = (real_off_diagonal[k - genus]
                             * shifted[i] * shifted[j])
            imag_terms[k] = (imag_off_diagonal[k - genus]
                             * u[i] * u[j])
        exponent = ctx.mpc(ctx.fsum(real_terms), ctx.fsum(imag_terms))
        term = ctx.exp(exponent)
        ratio = None
        if lower != upper:
            # Exact T(n + e0) / T(n) at the row's first point.
            ratio = ctx.exp(ctx.mpc(
                -two_pi * ctx.fsum(Y[0][i] * shifted[i]
                                   for i in range(genus)) - pi * Y[0][0],
                two_pi * ctx.fsum(X[0][i] * u[i]
                                  for i in range(genus))
                + pi * X[0][0] + imag_linear[0]))
        for value in range(lower, upper + 1):
            if value != lower:
                term *= ratio
                ratio *= ratio_step
                u[0] += 1
                for order in range(1, max_orders[0] + 1):
                    powers[0][order] = powers[0][order - 1] * u[0]
            for index, orders in enumerate(active_orders):
                if not orders:
                    sums[index].append(term)
                    continue
                i, order = orders[0]
                factor = powers[i][order]
                for i, order in orders[1:]:
                    factor *= powers[i][order]
                sums[index].append(factor * term)
    results = tuple(growth * degree_factors[degree] * ctx.fsum(terms)
                    for degree, terms in zip(degrees, sums))
    if _rtheta_is_real_slice(ctx, X, shift, a):
        # These derivatives are real on the real argument slice.
        results = tuple(ctx.mpc(ctx.re(result)) for result in results)
    return results


def _rtheta_sum(ctx, z, tau_key, a, b, derivatives, tau_data=None):
    """Evaluate one or more derivatives in one lattice traversal."""
    genus = len(z)
    if tau_data is None:
        tau_data = ctx._rtheta_tau_data(tau_key)
    X_key, Y_key, T, invT_frob, rho, value_radius = (
        tau_data[:6])
    Y = ctx.matrix(Y_key)
    y = ctx.matrix([ctx.im(value) for value in z])
    shift = ctx.lu_solve(Y, y)
    shift_tuple = tuple(shift[i] for i in range(genus))
    shift_norm = ctx.sqrt(ctx.fsum(value ** 2 for value in shift_tuple))
    degrees = tuple(sum(d) for d in derivatives)
    if all(degree == 0 for degree in degrees):
        radius = value_radius
    else:
        shift_bound = _shift_norm_bucket(ctx, shift_norm)
        radius = ctx._rtheta_derivative_radius(
            genus, tuple(sorted(set(degrees))), rho, invT_frob,
            shift_bound)
    center = tuple(-a[i] - shift_tuple[i] for i in range(genus))
    growth = ctx.exp(ctx.pi * ctx.fsum(y[i] * shift[i]
                                      for i in range(genus)))
    x_plus_b = tuple(ctx.re(z[i]) + b[i] for i in range(genus))

    if len(derivatives) == 1 and not any(derivatives[0]):
        value = _rtheta_value_sum(
            ctx, X_key, Y_key, T, center, radius, shift_tuple, a,
            x_plus_b, growth)
        return (value,)

    return _rtheta_derivative_sum(
        ctx, X_key, Y_key, T, center, radius, shift_tuple, a,
        x_plus_b, growth, derivatives)


# Evaluation selection and public interface
# -----------------------------------------

def _derivative_reduction_threshold(ctx, genus, degree, derivatives):
    """Estimate the point-count saving needed to reduce derivatives."""
    transformed_count = ctx.binomial(genus + degree, degree)
    requested_count = len(set(derivatives))
    # Quadratic-form and exponential evaluation is shared by every output and
    # costs at least as much as several derivative accumulations. Model that
    # common work as ``genus`` output-equivalents instead of charging the full
    # lattice traversal once for every member of the transformed jet. A larger
    # saving factor selects reduction less often.
    reduction_saving_factor = 4
    return (reduction_saving_factor * (genus + transformed_count)
            / (genus + requested_count))


def _rtheta_normalized_derivatives(ctx, z, tau_key, a, b, derivatives):
    """Evaluate normalized derivative requests with one selected traversal."""
    genus = len(z)
    max_degree = max(sum(derivative) for derivative in derivatives)
    input_magnitude = max([ctx.mag(value) for value in z + a + b]
                          + [0])
    # Increasing either guard improves cancellation resilience at a speed
    # cost. Ten bits per derivative level and two per input-magnitude bit are
    # deliberately modest because the tail bound has its own safety margin.
    derivative_guard_bits = 10
    input_guard_bits = 2
    extra = (derivative_guard_bits * (max_degree + 1)
             + input_guard_bits * max(0, input_magnitude))
    with ctx.extraprec(extra):
        use_reduction = False
        reduced_key = tau_key
        operations = ()
        tau_data = ctx._rtheta_tau_data(tau_key)
        direct_points = tau_data[6]
        # Reduction selection is deliberately empirical and affects speed,
        # not the truncation error. Do not pay its setup cost for 32 or fewer
        # estimated points, or when rho >= 0.9 indicates adequately separated
        # lattice points. Otherwise values require a fourfold point-count
        # saving; derivative jets use the cost model above because reduction
        # requires all transformed derivatives through ``max_degree``.
        minimum_reduction_points = 32
        separation_cutoff = ctx.mpf('0.9')
        value_reduction_saving = 4
        if (direct_points > minimum_reduction_points
                and tau_data[4] < separation_cutoff):
            reduced_key, operations, reduced_points = (
                ctx._rtheta_reduction_data(tau_key))
            if max_degree:
                required_saving = _derivative_reduction_threshold(
                    ctx, genus, max_degree, derivatives)
            else:
                required_saving = value_reduction_saving
            use_reduction = (direct_points / reduced_points
                             > required_saving)
        if use_reduction:
            if max_degree:
                results = _rtheta_reduced_derivatives(
                    ctx, z, tau_key, a, b, derivatives,
                    operations, reduced_key)
            else:
                transformed_z, characteristic_factor = (
                    _zero_characteristic_form(ctx, z, tau_key, a, b))
                transformed_z, modular_factor = _apply_reduction(
                    ctx, transformed_z, operations)
                transformed_z, argument_factor, _unused_shift = (
                    _reduce_zero_argument(ctx, transformed_z, reduced_key))
                zeros = (ctx.zero,) * genus
                values = _rtheta_sum(
                    ctx, transformed_z, reduced_key, zeros, zeros,
                    derivatives)
                factor = (characteristic_factor * modular_factor
                          * argument_factor)
                results = tuple(factor * value for value in values)
        else:
            results = _rtheta_sum(
                ctx, z, tau_key, a, b, derivatives, tau_data)
    return tuple(+value for value in results)


def _normalise_rtheta_inputs(ctx, z, tau, characteristic):
    """Validate common Riemann theta inputs and return immutable values."""
    tau = _normalise_tau(ctx, tau)
    genus = tau.rows
    z = _as_vector(ctx, z, "z", genus)
    a, b = _normalise_characteristic(ctx, characteristic, genus)
    return z, _matrix_tuple(tau), a, b


def _rtheta_derivatives(ctx, z, tau, characteristic, derivatives):
    """Evaluate several public-format derivative requests in one traversal."""
    z, tau_key, a, b = _normalise_rtheta_inputs(
        ctx, z, tau, characteristic)
    genus = len(z)
    try:
        derivatives = tuple(derivatives)
    except TypeError:
        raise ValueError("derivatives must be a nonempty sequence")
    if not derivatives:
        raise ValueError("derivatives must be a nonempty sequence")
    derivatives = tuple(_normalise_derivative(derivative, genus)
                        for derivative in derivatives)
    return _rtheta_normalized_derivatives(
        ctx, z, tau_key, a, b, derivatives)


@defun
def rtheta(ctx, z, tau, characteristic=None, derivative=0):
    r"""
    Evaluates the Riemann theta function of the vector :math:`z` and Riemann
    matrix :math:`\tau`. In genus :math:`g`, the convention is

    .. math ::

        \theta(z\mid\tau) = \sum_{n\in\mathbb Z^g}
        \exp(\pi i n^T\tau n + 2\pi i n^Tz).

    The argument :math:`z` must be a length-:math:`g` sequence or an mpmath
    column matrix. The period matrix :math:`\tau` must be a square nested
    sequence or mpmath matrix. It must be symmetric and its imaginary part
    must be positive definite. Entries opposite the diagonal that differ
    only by the current ``almosteq`` tolerance are averaged; materially
    asymmetric matrices raise ``ValueError``.

    **Characteristics**

    Passing ``characteristic=(a, b)`` evaluates

    .. math ::

        \theta\!\begin{bmatrix}a\\b\end{bmatrix}(z\mid\tau)
        = \sum_{n\in\mathbb Z^g}
        \exp\!\left(\pi i(n+a)^T\tau(n+a)
        +2\pi i(n+a)^T(z+b)\right).

    Here :math:`a` and :math:`b` are literal length-:math:`g` real vectors,
    rather than packed characteristic bits. Arbitrary real characteristics
    are accepted; half-integer characteristics are the most common.

    **Derivatives**

    ``derivative=(d0, ..., d(g-1))`` requests the multi-index derivative

    .. math ::

        \frac{\partial^{d_0+\cdots+d_{g-1}}\theta}
        {\partial z_0^{d_0}\cdots\partial z_{g-1}^{d_{g-1}}}.

    The entries must be nonnegative integers. In genus one, an integer
    derivative order can be supplied directly for consistency with
    ``jtheta``. Derivatives are with respect to the components of :math:`z`,
    not the angular argument used by ``jtheta``.

    **Examples**

    Evaluate a genus-two theta value::

        >>> from mpmath import mp, rtheta
        >>> mp.dps = 15
        >>> mp.pretty = True
        >>> tau = [[1.0j, 0.05j], [0.05j, 1.2j]]
        >>> rtheta([0.1, 0.2], tau)
        (1.08592896533944 + 0.0j)

    A half-characteristic and a mixed derivative use literal vectors and a
    derivative multi-index::

        >>> characteristic = ([0.5, 0], [0, 0.5])
        >>> rtheta([0.1, 0.2], tau, characteristic, derivative=(1, 1))
        (-0.289794493099238 + 0.0j)

    In genus one, set :math:`q=\exp(\pi i\tau)` and write :math:`z=w/\pi`.
    The four standard Jacobi theta functions then correspond to

    .. math ::

        \begin{aligned}
        \theta\!\begin{bmatrix}1/2\\1/2\end{bmatrix}
            (w/\pi\mid\tau) &= -\vartheta_1(w,q), &
        \theta\!\begin{bmatrix}1/2\\0\end{bmatrix}
            (w/\pi\mid\tau) &= \vartheta_2(w,q), \\
        \theta\!\begin{bmatrix}0\\0\end{bmatrix}
            (w/\pi\mid\tau) &= \vartheta_3(w,q), &
        \theta\!\begin{bmatrix}0\\1/2\end{bmatrix}
            (w/\pi\mid\tau) &= \vartheta_4(w,q).
        \end{aligned}

    For example, the zero-characteristic identity can be checked directly::

        >>> from mpmath import almosteq, expjpi, jtheta, pi
        >>> tau1 = mp.mpc('0.2', '0.9')
        >>> w = mp.mpc('0.3', '0.1')
        >>> almosteq(rtheta([w/pi], [[tau1]]),
        ...          jtheta(3, w, expjpi(tau1)))
        True

    **Accuracy**

    The truncation controls absolute error in the scaled series. Near a zero
    of theta, cancellation can prevent full relative accuracy.

    **Performance**

    This implementation is intended primarily for low-genus applications.
    Computation time depends strongly on :math:`\tau` and can increase
    rapidly with the genus and requested precision. Automatic reduction can
    make many otherwise slow inputs practical, but general high-genus
    evaluation may remain expensive.

    **References**

    1. [DLMF]_ Chapter 21, Multidimensional Theta Functions.
    2. B. Deconinck, M. Heil, A. Bobenko, M. van Hoeij and M. Schmies,
       *Computing Riemann Theta Functions*, Mathematics of Computation 73
       (2004), 1417-1442.

    """
    return _rtheta_derivatives(
        ctx, z, tau, characteristic, (derivative,))[0]


@defun
def rtheta_jet(ctx, z, tau, order, characteristic=None):
    r"""
    Evaluates a derivative jet of the Riemann theta function. A jet is the
    function value together with all partial derivatives through the
    requested total order at the same point.

    For example, in genus two the order-two jet aligns the multi-indices and
    derivatives as follows (all evaluated at the same :math:`z`):

    .. math ::

        \begin{gathered}
        \big((0,0),(1,0),(0,1),(2,0),(1,1),(0,2)\big) \\
        \left(\theta,
        \frac{\partial\theta}{\partial z_0},
        \frac{\partial\theta}{\partial z_1},
        \frac{\partial^2\theta}{\partial z_0^2},
        \frac{\partial^2\theta}{\partial z_0\partial z_1},
        \frac{\partial^2\theta}{\partial z_1^2}\right)
        \end{gathered}.

    ``order`` must be a nonnegative integer. The result is a dictionary
    mapping each derivative multi-index to its value. Its keys are inserted
    in graded reverse lexicographic order: total order first, then the
    earlier coordinates first within each order. For example, an order-two
    genus-two jet has the keys

    .. code-block:: text

        (0, 0), (1, 0), (0, 1), (2, 0), (1, 1), (0, 2)

    Values are ordinary derivatives, using the same convention as the
    ``derivative`` argument to :func:`~mpmath.rtheta`; they are not divided
    by multi-index factorials. All components are accumulated in one lattice
    traversal, which is normally much faster than separate calls to
    :func:`~mpmath.rtheta`.

    **Examples**

    Evaluate a value, gradient and Hessian components together::

        >>> from mpmath import almosteq, rtheta, rtheta_jet
        >>> tau = [[1.0j, 0.05j], [0.05j, 1.2j]]
        >>> z = [0.1, 0.2]
        >>> jet = rtheta_jet(z, tau, 2)
        >>> list(jet)
        [(0, 0), (1, 0), (0, 1), (2, 0), (1, 1), (0, 2)]
        >>> almosteq(jet[(1, 1)], rtheta(z, tau, derivative=(1, 1)))
        True

    Characteristics use the same literal ``(a, b)`` convention as
    :func:`~mpmath.rtheta`.

    """
    if not isinstance(order, int) or order < 0:
        raise ValueError("order must be a nonnegative integer")
    z, tau_key, a, b = _normalise_rtheta_inputs(
        ctx, z, tau, characteristic)
    derivatives = tuple(_multiindices(len(z), order))
    values = _rtheta_normalized_derivatives(
        ctx, z, tau_key, a, b, derivatives)
    return dict(zip(derivatives, values))
