name: Linting with ruff, etc
on: [workflow_dispatch, workflow_call]
jobs:
  linter:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v7
        with:
          python-version: "3.x"
      - uses: j178/prek-action@v3.0.0
