name: test
on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 2'
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  linter:
    uses: ./.github/workflows/linter.yml
  coverage:
    uses: ./.github/workflows/coverage.yml
  docs:
    uses: ./.github/workflows/docs.yml
  frozen-version:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v7
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v7
      with:
        python-version: "3.x"
    - name: Run frozen version test
      run: ./mpmath/tests/test_version_frozen.sh
  tests:
    needs:
      - linter
      - coverage
      - frozen-version
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', 3.11, 3.12, 3.13, 3.14, 3.14t, 3.15, 3.15t]
        nogmpy: [false]
        purepy: [false]
        include:
          - python-version: "3.x"
            nogmpy: true
          - python-version: "3.x"
            purepy: true
          - python-version: pypy3.11
            purepy: true
          - python-version: graalpy-25
            purepy: true
          - python-version: pypy3.11-nightly
            nogmpy: true
    env:
      PYTEST_ADDOPTS: -n auto --durations=20
    steps:
    - uses: actions/checkout@v7
      with:
        fetch-depth: 0
    - run: sudo apt-get update
    - run: sudo apt-get install zlib1g-dev libjpeg8-dev
    - run: |
        ZZ_VERSION=0.8.0
        ZZ_DIR=zz-${ZZ_VERSION}
        GITHUB_URL=https://github.com/diofant/zz/releases/download/
        ZZ_URL=${GITHUB_URL}v${ZZ_VERSION}/${ZZ_DIR}.tar.gz
        wget ${ZZ_URL}
        tar xzf ${ZZ_DIR}.tar.gz
        cd ${ZZ_DIR}
        ./configure -q
        make
        sudo make install
      if: matrix.nogmpy && (matrix.python-version == 'pypy3.11-nightly')
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v7
      with:
        python-version: ${{ matrix.python-version }}
        allow-prereleases: true
    - run: pip install --upgrade setuptools pip
    - name: Install dependencies
      run: |
        pip install --upgrade .[develop,gmpy2,gmp,ci]
      if: ${{ matrix.nogmpy != true }}
    - run: pip install --upgrade .[develop,gmp,ci]
      if: matrix.nogmpy
    - run: pip uninstall -y gmpy2
      if: matrix.nogmpy
    - run: pip uninstall -y gmpy2 python-gmp
      if: matrix.purepy
    - run: pytest
